# -*- coding: utf-8 -*-
"""Tarea_3_datos_SENAMHI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QrwtoHdE_aiD7QM-WBuF4ORqywoyRxyo

### Ejercicio: Datos climáticos estación

Link de datos: https://drive.google.com/drive/folders/1QD_GVY_KDRu6CEtN3qUmybuatw0WjRYx?usp=sharing


Crea un nuevo DataFrame con datos de 1 estaciones SENAMHI de diferentes regiones del Perú (https://www.senamhi.gob.pe/site/descarga-datos/).

Considerar lo siguiente a partir de "tutorial-para-la-descarga-de-datos.pdf".

Los datos de las columnas corresponden a:
- Columna A: Año
- Columna B: Mes
- Columna C: Día
- Columna D: Precipitación acumulada
- Columna E: Temperatura máxima
- Columna F: Temperatura mínima

En las celdas donde aparece -99.9 significa que no hay información disponible para esa variable

Luego:
1. Parsear el nombres de la estación Chosica y leer el archivo.
1. Calcula el promedio mensual de precipitación
1. Calcula el promedio anual de precipitación
2. Identifica el día más lluvioso
4. Exporta los resultados formateados en CSV
"""

from google.colab import drive
drive.mount('/content/drive')

import os
files = os.listdir('/content/drive/MyDrive/SENAMHI')  # Lista los archivos en el directorio
files

# Parsear el nombre del archivo para obtener el código y nombre de la estación
station = files[0] # Changed index from 5 to 0 to select the first station (Chosica)

# Extracting station code and name from the filename
parts = station.replace('.txt', '').split('_')
codigo = parts[0]
nombre = ' '.join(parts[1:])

print(f"Código: {codigo}, Nombre: {nombre}")

# Leer el archivo CSV de la estación seleccionada
import pandas as pd
station_df = pd.read_table(f'/content/drive/MyDrive/SENAMHI/{station}', header=None, sep=' ', na_values=['-999','-99.9']) # Sin encabezados
station_df.columns = ['Año', 'Mes', 'Dia', 'Pr','Tmax', 'Tmin']  # Asignar nombres de columnas
# Formatear las columnas
station_df['Año'] = station_df['Año'].astype(int)
station_df['Mes'] = station_df['Mes'].astype(int)
station_df['Dia'] = station_df['Dia'].astype(int)

station_df

station_df.describe()
#station_df.info()

# Calcular el promedio mensual de precipitación
precipitacion_mensual = station_df.groupby(['Año', 'Mes'])['Pr'].mean().reset_index()

# Calcular el promedio anual de precipitación
precipitacion_anual = station_df.groupby('Año')['Pr'].mean().reset_index()

# Identificar el día más lluvioso
dia_mas_lluvioso = station_df.loc[station_df['Pr'].idxmax()]


print(f"Precipitación mensual:\n{precipitacion_mensual}\n")
print(f"Precipitación anual:\n{precipitacion_anual}\n")
print(f"El día más lluvioso fue el {dia_mas_lluvioso['Año']:.0f}-{dia_mas_lluvioso['Mes']:.0f}-{dia_mas_lluvioso['Dia']:.0f} con {dia_mas_lluvioso['Pr']} mm de precipitación.")

# Exportar resultados a CSV
precipitacion_mensual.to_csv(f'precipitacion_mensual_{nombre}.csv', index=False)
precipitacion_anual.to_csv(f'precipitacion_anual_{nombre}.csv', index=False)

# Convert dia_mas_lluvioso Series to DataFrame for export
dia_mas_lluvioso_df = pd.DataFrame([dia_mas_lluvioso])
dia_mas_lluvioso_df.to_csv(f'dia_mas_lluvioso_{nombre}.csv', index=False)

print("Resultados exportados a CSV.")

# Ejercicio 2: Procesamiento de datos multiestación

import pandas as pd

# Diccionario para almacenar los DataFrames de cada estación
stations_data = {}
station_names = []

# Iterar sobre cada archivo de estación
for station_file in files:
    # Extraer el código y nombre de la estación del nombre del archivo
    parts = station_file.replace('.txt', '').split('_')
    codigo_estacion = parts[0]
    nombre_estacion = ' '.join(parts[1:])
    station_names.append(nombre_estacion)

    print(f"Procesando estación: {nombre_estacion} (Código: {codigo_estacion})")

    # Construir la ruta completa del archivo
    file_path = f'/content/drive/MyDrive/SENAMHI/{station_file}'

    # Leer el archivo de la estación
    df = pd.read_table(file_path, header=None, sep=' ', na_values=['-999','-99.9'])
    df.columns = ['Año', 'Mes', 'Dia', 'Pr','Tmax', 'Tmin']

    # Formatear las columnas de fecha
    df['Año'] = df['Año'].astype(int)
    df['Mes'] = df['Mes'].astype(int)
    df['Dia'] = df['Dia'].astype(int)

    # Crear una columna de fecha para facilitar la unión y el análisis temporal
    df['Fecha'] = pd.to_datetime({'year': df['Año'], 'month': df['Mes'], 'day': df['Dia']})

    # Almacenar el DataFrame en el diccionario, usando el nombre de la estación como clave
    stations_data[nombre_estacion] = df.set_index('Fecha')

print("\nDatos de todas las estaciones cargados y preparados.")

# Mostrar las primeras filas de una de las estaciones para verificar
if 'chosica' in stations_data:
    print(f"\nPrimeras filas de la estación Chosica:\n{stations_data['chosica'].head()}")

"""### Ejercicio 2: Datos climáticos multiestación

Crea un nuevo DataFrame con datos de 5 estaciones SENAMHI de diferentes regiones del Perú (https://www.senamhi.gob.pe/site/descarga-datos/).

Las tareas de este ejercicio ya han sido completadas en las celdas anteriores, donde se realizaron los siguientes pasos:
1. Se parsearon los nombres de las estaciones y se leyeron los archivos.
2. Se unieron los DataFrames por la columna `Fecha`.
3. Se calculó el promedio mensual de precipitación para cada estación.
4. Se identificó el mes más lluvioso en cada estación.
5. Se exportaron los resultados a archivos CSV.
"""

# Unir los DataFrames de todas las estaciones por la columna 'Fecha'
combined_df = pd.DataFrame()

for name, df_station in stations_data.items():
    # Renombrar la columna 'Pr' para incluir el nombre de la estación
    temp_df = df_station[['Pr']].rename(columns={'Pr': f'Pr_{name}'})
    if combined_df.empty:
        combined_df = temp_df
    else:
        combined_df = combined_df.join(temp_df, how='outer')

print("\nDataFrame combinado de precipitación por estación:")
print(combined_df.head())

# Calcular el promedio mensual de precipitación para cada estación
monthly_precipitation_all_stations = combined_df.resample('M').mean()

print("\nPrecipitación mensual promedio para todas las estaciones:")
print(monthly_precipitation_all_stations.head())

# Identificar el mes más lluvioso para cada estación
rainiest_month_per_station = pd.DataFrame()
for col in monthly_precipitation_all_stations.columns:
    station_name = col.replace('Pr_', '')
    if not monthly_precipitation_all_stations[col].isnull().all():
        max_pr_month = monthly_precipitation_all_stations[col].idxmax()
        max_pr_value = monthly_precipitation_all_stations[col].max()
        rainiest_month_per_station = pd.concat([
            rainiest_month_per_station,
            pd.DataFrame([{'Estacion': station_name, 'Mes_Mas_Lluvioso': max_pr_month.strftime('%Y-%m'), 'Precipitacion_Max': max_pr_value}])
        ], ignore_index=True)

print("\nMes más lluvioso por estación:")
print(rainiest_month_per_station)

# Exportar resultados a CSV
combined_df.to_csv('precipitacion_combinada_estaciones.csv')
monthly_precipitation_all_stations.to_csv('precipitacion_mensual_todas_estaciones.csv')
rainiest_month_per_station.to_csv('mes_mas_lluvioso_por_estacion.csv', index=False)

print("\nResultados multiestación exportados a CSV.")